// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnKofB3PmzENeBmRdGKGkJ_akZn7VNWD8',
    appId: '1:793952716460:web:410a2990f97dcd49154109',
    messagingSenderId: '793952716460',
    projectId: 'uas-platform-879c7',
    authDomain: 'uas-platform-879c7.firebaseapp.com',
    storageBucket: 'uas-platform-879c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZWBSZB7Kph1_m-bO25BApPxJ8wZpDhhg',
    appId: '1:793952716460:android:ba115b1e012af43f154109',
    messagingSenderId: '793952716460',
    projectId: 'uas-platform-879c7',
    storageBucket: 'uas-platform-879c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbrd9N5puMAtCxEeWGY8MI9QWO5NhEBxg',
    appId: '1:793952716460:ios:ed52832701d55d3f154109',
    messagingSenderId: '793952716460',
    projectId: 'uas-platform-879c7',
    storageBucket: 'uas-platform-879c7.firebasestorage.app',
    iosBundleId: 'com.example.appMahasiswa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnKofB3PmzENeBmRdGKGkJ_akZn7VNWD8',
    appId: '1:793952716460:web:417ec86d809400f1154109',
    messagingSenderId: '793952716460',
    projectId: 'uas-platform-879c7',
    authDomain: 'uas-platform-879c7.firebaseapp.com',
    storageBucket: 'uas-platform-879c7.firebasestorage.app',
  );
}
